title: "Mateusz Lisiecki Portfolio"
description: "Data Analyst with a passion for data-driven decision making."
url: "https://matlis.github.io"  # Your GitHub Pages URL stays the same
theme: minimal-mistakes
