title: "Mateusz Lisiecki Portfolio"
description: "Data Analyst with a passion for data-driven decision-making."
url: "https://matlis-purple.github.io" # Keep this as your GitHub Pages URL (if it's still 'matlis-purple')
theme: minimal-mistakes
